### ISSUE TITLE
Decide approach for style sheets - migrate styling

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-mechanism-finder#19]
Decide approach (e.g. scss, stylable) for handling styling and remove existing-in line syling out of components

**Comment by tomzemp** [comment]
Classes are being rendered differently from within dhis2 (dev-tom.datim)

![image](https://user-images.githubusercontent.com/18490902/60579274-07e16780-9d83-11e9-8a89-c045e84bb5df.png)

Then when running locally:
![image](https://user-images.githubusercontent.com/18490902/60579315-1a5ba100-9d83-11e9-80b9-aa04c07ba3ae.png)

This is causing the display to vary wildly when on dhis2 server (see e.g. https://github.com/pepfar-datim/datim-mechanism-finder/issues/27#issuecomment-507772785)

Need to investigate/fix. Maybe adding MUI wrapper will be sufficient, or maybe need to move away from styling with @material-ui/styles hooks (https://material-ui.com/styles/basics/)

**Comment by tomzemp** [comment]
@benguaraldi @jakub-bao: I redid the styling by using vanilla in-line styling on the components rather than trying to use Material-UI's makeStyles...it seems to achieve the same thing, and be roughly similar in terms of where the styling lives, but it doesn't result in problems when loaded in an actual DHIS2 instance as far as I can see.

I've put this on `redoStyles` branch in case you want to weigh in on this alternative approach

**Comment by benguaraldi** [comment]
@tomzemp Much better!  Thank you for tracking that down!  Sorry that it was super-annoying.

I don't know if these are easy fixes or if you want additional tickets for them, but two things:
- If the IM and Legacy Partner Name could default to twice the width of the other columns, that would be great
- We have to scroll down to the bottom of the table to scroll across the table—I feel like there was a fix for this in the previous version, where the page was the width of the table?  Let me know if you want more clarification on this

I'm fine with postponing those both to after the MVP

**Comment by tomzemp** [comment]
@benguaraldi: updated the column widths 
![image](https://user-images.githubusercontent.com/18490902/63790603-e8396c00-c8f9-11e9-8922-d01159df746f.png)

Changing the scroll is unfortunately difficult so far as I can tell :-(

**Comment by tomzemp** [comment]
Thanks for noticing that @benguaraldi! I guess I was just looking at the first couple of columns.

I've fixed and redeployed on dev-tom.datim
![image](https://user-images.githubusercontent.com/18490902/63934040-c3a8d580-ca5a-11e9-97e7-9be24af63362.png)

**Comment by tomzemp** [comment]
This issue has been completed;

scroll bar mentioned in comments is on separate issue:
https://github.com/pepfar-datim/datim-mechanism-finder/issues/16
