### ISSUE TITLE
Header Updates in FACTS Info Table

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-mechanism-finder#35]
@mjenije  requested that 
`HQ ID` header be changed to `Mech ID`
`IM` header be changed to `Mech Name`

![image](https://user-images.githubusercontent.com/18490902/64866340-8720d080-d63b-11e9-88c0-ce8d5e6775fe.png)

@benguaraldi: I assume that you want to just make this change on the Front-End and not

**Comment by benguaraldi** [comment]
@tomzemp I think it probably makes more sense to make this change on sync.datim.org.  Let's go ahead and deploy the app without this and then we can do the change there and the app will pick it up.

**Comment by tomzemp** [comment]
After discussion with @benguaraldi, we decided that it was easier to update the header names on the front end rather than the back end as we were already addressing the column order (#38) and hence it's easier to keep to column names consistent on the back end, as the ordering expects certain names on the back end.

So...on front end we order with the existing names, then rename `HQ ID` to `Mech ID` and `IM` to `Mech Name`

**Comment by tomzemp** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/18490902/65233387-08141800-dad3-11e9-9a48-18d9cc852348.png)
