### ISSUE TITLE
Reorder columns in FACTS Info Table

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-mechanism-finder#38]
@mjenije wanted to know if it's possible to reorder the columns to group similar items like OU and OU Country Code.

@benguaraldi: if we wanted to do this, I assume you'd want to just implement on the front end rather than the back end feed. I think this is probably feasible (though not minimal effort). There'd need to be some logic to check the desired order against the headers that actually come back from FACTs Feed.

**Comment by tomzemp** [comment]
@mjenije: FYI here are the current column names (in the current order)

Date
OU
FY
Reporting Cycle
HQ ID
Legacy ID
IM
Agency
Legacy Partner Name
Legacy Partner ID
Start Date
End Date
Active
Award Number
Partner DUNS
Partner Country
Indigenous Partner
Organization Type
Legacy Partner Organization Type ID
OU Country Code
Partner Name

**Comment by mjenije** [comment]
@tomzemp Preposed order:

Date
OU
OU Country Code
FY
Reporting Cycle
HQ ID
IM
Agency
Award Number
Partner Name
Partner DUNS
Start Date
End Date
Active
**Partner Country
Indigenous Partner
Organization Type**
Legacy ID
Legacy Partner Name
Legacy Partner ID
Legacy Partner Organization Type ID

The items in bold thematically make more sense following Partner DUNS, but its information that is less useful for users looking up a Mech in DATIM. So I grouped them at the end of the list of new data before the Legacy items. Thanks!

**Comment by tomzemp** [comment]
Done:

![image](https://user-images.githubusercontent.com/18490902/65233155-a94e9e80-dad2-11e9-8e37-e187ee39c75b.png)
